language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt -r requirements-dev.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "zmofO6rJV8r2VBlHxgPcJ4MRVOx1uelLeIXy9BbSHAT6oZmrlAehmY8ifMKU1cdrtv19xdciLLE+LnzwUw/9REB9jJ75dQgUepVQSDlKFaj0vnZw3Xnu8YII2MBJ/hjt6n23SbM4SDEF+ipEPiQde6nhg91S/Buuo9VRLglLDt6MX4xBbKPeSpU9tJuBauzVFMDhK2tSJlbwEzMKHVroP2L+MxTKl0skhKiBiMDkrPjpVAPdURZ2ZQ0/Iwgin1/g80GFXWhqzcojB1aTUW8SJMZU+20fD0zzn+Jpssl4MXo9TyacsR65XCXXlk+cZokckMDa/bTgUMAL//UF5ix9t06tDBntBwfzjMxRzIej3UY4y+xLsp7QmHB6Es1uZH2R72h+L9P9D4KKdBXgQ6yKfPAw4ujdKhBoUqbLmj9niZ8Otb+/MtPpKu6nEDwsLT0U7p8zigI/SpNdvegzYCsirRqtDH89PZd7P8sAHbay++VmIGyRoQk93HyD5h4Rd6/OQw46x+nUhDhPX9uEEug6V1AXrCJhfh5h2oyuGU3gfF6JY9ONNxm8wlWEUACR0eIbHZhH5joOMUQsFeex+FKiY2JexAtuMr8W5pqCfS8gK1U+O/hbXViwGFBsgJmMFV1ZJkpU7FiFdmSCjIaQS84qIoWyQyC39PWvLLlGMYPj8eI="

script:
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
